### ISSUE TITLE
Обрезаются ссылки .рф 

### ISSUE THREAD

**Issue by vpArth** [ingniq/medinteh#1]
https://github.com/ingniq/medinteh/blob/3d08845183c7cb0f4251e26bb29227f0067ecb70/app/ShortUrl.php#L223

```php
$url = 'http://президент.рф/';
echo $url = filter_var($url, FILTER_SANITIZE_URL);
// http://./
```

**Comment by ingniq** [comment]
Да, требует доработки. Кириллические домены предварительно конвертировать через Punycode

**Comment by vpArth** [comment]
Нет, думаю проще упростить процесс валидации) В конце концов, это проблема пользователя, что его косячная ссылка потом не будет работать :)
