### ISSUE TITLE
Ненужная зависимость

### ISSUE THREAD

**Issue by vpArth** [ingniq/medinteh#2]
https://github.com/ingniq/medinteh/blob/3d08845183c7cb0f4251e26bb29227f0067ecb70/app/ShortUrl.php#L57-L58

Отвратительно ;) Стоит инжектировать зависимость:

```php
	public function __construct(Data $data)
	{
		$this->_db = $data;
		$this->_timestamp = $_SERVER["REQUEST_TIME"];
	}
```

**Comment by ingniq** [comment]
Пожалуй))
