### ISSUE TITLE
Не возвращается короткая ссылка при коллизии

### ISSUE THREAD

**Issue by vpArth** [ingniq/medinteh#3]
https://github.com/ingniq/medinteh/blob/3d08845183c7cb0f4251e26bb29227f0067ecb70/app/ShortUrl.php#L168-L171

Должно быть хотя бы так:

```php
if ($this->_db->select('short_url', $short, true)) { 
  return $this->createShortCode(); 
}

**Comment by ingniq** [comment]
Думал над этим, но может быть не допонял) Думал так, что здесь возврат данных не нужен, здесь нужен только вызов метода. В конце концов в случае НЕ срабатывании условия вернется конечный результат работы метода, что нам и нужно. Хотя видимо результат должен вернуться в "предыдущую" итерацию, так сказать..

**Comment by vpArth** [comment]
> вернется конечный результат работы метода

Вернётся именно тот сгенерированный ключ, который вызвал коллизию. Результаты работы рекурсивного вызова просто игнорируются.
