### ISSUE TITLE
Как войти с другими реквизитами?

### ISSUE THREAD

**Issue by vpArth** [ingniq/medinteh#4]
https://github.com/ingniq/medinteh/blob/3d08845183c7cb0f4251e26bb29227f0067ecb70/app/Data.php#L37-L39

Такие вещи нужно инжектить:   
```php
 public function __construct($host, $db_name, $user, $pass) 
 { 
   $mysqli = new mysqli($host, $db_name, $user, $pass);
 }
```
Или:
```php
 public function __construct(array $cfg) 
 { 
   $mysqli = new mysqli($cfg['host'], $cfg['user'], $cfg['pass'], $cfg['db']);
 }
```
Или создать специальный интерфейс конфигурации базы, но это, скорее всего было бы оверинжинирингом.

**Comment by ingniq** [comment]
Хорошо
