### ISSUE TITLE
Повторный поход в базу, зачем?

### ISSUE THREAD

**Issue by vpArth** [ingniq/medinteh#5]
https://github.com/ingniq/medinteh/blob/3d08845183c7cb0f4251e26bb29227f0067ecb70/app/ShortUrl.php#L93

Думаю, стоило выбрать сразу то, что нужно при проверке существования.

**Comment by ingniq** [comment]
Тоже думал над этим, нужно ли. Сделать менее затратный запрос к БД, а потом более сложный при успешном выполнении первого... В нашем случае смысла нет, согласен.
